- cluster.yml
- galaxy-requirements.yml
Add the epel repo to the jumphost.
This is nessecary as it has no spacewalk connection.
> Add the epel repo to the jumphost.

- roles/slurm/meta/main.yml
Mariadb is needed for slurm (obviously)
> added missing mariadb dependency

- cluster.yml
- group_vars/gearshift/vars.yml
Made ansible install above roles likely to fail
imported variables that are needed for slurm in the groupvars of
gearshift.
> Made ansible install above roles likely to fail.

- roles/ldap/files/ssh-ldap-wrapper
Without this fix only the last public key fetched from the LDAP will work: silly!
> Bugfix: parse public keys correctly for OpenSSH no matter in which order they are supplied from the LDAP.

- heat/talos.yml
.The ui needs this to be able to mount isilon and datahandling exports in the storage vlan.
> Added a network interface for thalos

- group_vars/gearshift-cluster/vars.yml
- roles/ldap/templates/ldap.conf
- roles/ldap/templates/nslcd.conf
- single_role_playbooks/ldap.yml
tested on gs-vcompute01
```
[egon@gs-vcompute01 ~]$ id umcg-hjtest
uid=50100844(umcg-hjtest) gid=50100844(umcg-hjtest) groups=50100844(umcg-hjtest)
```
Aanpassingen in /etc/nscld.conf
base ou=research,o=asds
#filter op scz entitlement of umcg
filter passwd (|(rugpersonentitlementvalue=scz)(rugpersonentitlementvalue=umcg))
filter shadow (|(rugpersonentitlementvalue=scz)(rugpersonentitlementvalue=umcg))
#extra check om alleen umcg mensen toe te laten en SCZ mensen die in de groep gearshift zitten
pam_authz_search (|(&(objectClass=posixGroup)(cn=co_bbmri_g-GRP_Gearshift)(memberUid=$username))(&(cn=$username)(rugpersonentitlementvalue=umcg)))
Aanpassingen in /etc/ssh/ldap.conf
base ou=research,o=asds
```
> Added changes for federated login. 

- host_vars/imperator
- roles/cluster/templates/gearshift_hosts
> Add the fysical cluster nodes in /etc/hostsi

- group_vars/all/vars.yml
- group_vars/talos-cluster/vars.yml
- roles/logins/files/login_checks.sh
- roles/logins/tasks/main.yml
- roles/slurm-client/tasks/main.yml
- roles/slurm/files/job_submit.lua
- roles/slurm/tasks/main.yml
* Bugfix: use correct name for tmp LFS on Talos.
* Improved login checks to create users and accounts in the Slurm accounting DB by relocating this functionality from login to job submission time.
* Fixed typo in task name in slurm role.
* Bugfix: /var/spool/slurmd must be owned by root.
* Bugfix: /var/spool/slurmd must be readable, but not writable for all users.
> Bugfixes and improved version of login checks

- roles/ldap/templates/nslcd.conf
This sets the default shell to bash for all ldap users.
> Make bash the default shell.

- callback_plugins/homsaplog.py
- group_vars/gearshift-cluster/vars.yml
- group_vars/talos-cluster/vars.yml
- inventory.py
- roles/figlet_hostname/tasks/main.yml
* Python 2 -> 3 upgrade compatibility fixes / workarounds for:
* callback_plugins/homsaplog.py
* inventory.py dynamic inventory script.
* Added scheduled maintenance warning + dates to motd for Talos and Gearshift
* Use figlet on deploy target as opposed to Ansible control machine.
> Made python scripts compatible with Python 3 and improved figlet + motd

- .gitignore
- group_vars/all/vars.yml
- group_vars/fender-cluster/vars.yml
- group_vars/hyperchicken-cluster/vars.yml
* Updated .gitignore to exclude key pairs with "production" in their file names.
* Added standard cloud image user named "centos" for CentOS based images.
* Added "centos" user with home relocated to /admin/centos to config for Hyperchicken and Fender to rescue this local admin user when home dirs from shared storage are mounted in /home.
> Prevent getting locked out of account for default cloud image user

- roles/shared_storage/tasks/main.yml
To make sure new files and subfolders inherit the group.
> Bugfix: add S bit to group folders.

- group_vars/administration.yml
- host_vars/all.yml
- inventory.py
- proxy.yml
- roles/cluster/defaults/main.yml
- roles/cluster/files/skel/.bashrc
- roles/ldap/defaults/main.yml
- roles/mount-volume/defaults/main.yml
- roles/mount-volume/tasks/main.yml
- roles/online_docs/tasks/main.yml
- roles/shared_storage/tasks/main.yml
* Bugfix for ```online_docs``` role: fixed wrong error message when rsync is too old.
* Removed unused playbook file ```proxy.yml```
* Relocated ```sshd_moduli_minimum``` default from ```ldap``` to ```cluster``` role, because the rest of the sshd config was already relocated to that role.
* Bugfix: default name for inventory file was not parsed correctly by dynamic inventory script.
* Updated ```skel/.bashrc``` for changes in HPC environment deployed with ```ansible-pipelines``` repo.
* Bugfix for ```mount-volume ```role: make sure local volumes are mounted with the correct permissions for the users that need to work with these mounts.
* Bugfix for ```shared_storage``` role: fix wrong permissions due to missing quotes.
> Various assorted bugfixes

- group_vars/all/vars.yml
I still think a double firewall (openstack and local iptables) is very cumbersome.
And I still think the openstack firewall is much more user-friendly.
But in the meantime i'd like to access my metrics.
> Allow incoming traffic to node_exporter

- roles/slurm-management/meta/main.yml
- roles/slurm-management/tasks/main.yml
Mariadb depends on docker & munge needs to be setup on the slurm-management node.
> Mariadb depends on docker & munge needs to be setup on the slurm-management node.

- roles/shared_storage/tasks/main.yml
The NFS server should not mount its own storage. 
Although an exclusion rule is not very nice, I could not think of a better way to do this.
> The NFS server should not mount its own storage.

- cluster.yml
Moved the setup of spacewalk and EPEL to the front, because these repositories are needed earlier for the installation of pam_script.
> Moved the setup of spacewalk and EPEL to the front.

- roles/slurm-client/tasks/main.yml
The package warewulf-nhc has been renamed into lbnl-nhc in newer versions.
> The package warewulf-nhc has been renamed into lbnl-nhc.

- cluster.yml
- roles/sshd/templates/sshd_config
Gerben found that the new ldap wrapper could lead to a situation where both local and ldap accounts are locked out from logging in. 
This branch fixes this by
1) Ensuring the dependencies of the ldap wrapper are installed even on the jumphost which is not on spacewalk.
2) In the case of failure of the ldap wrapper, sshd should look up the local keys for local admin users.
> Prevent the playbook from locking you out.

- cluster.yml
- roles/docker/tasks/main.yml
- roles/prom_server/handlers/main.yml
- roles/prom_server/meta/main.yml
- roles/prom_server/tasks/main.yml
- single_role_playbooks/prom_server.yml
* Use explicit become for all tasks in ```prom_server``` and ```docker``` roles.
* Added single_role playbook for ```prom_server``` role.
* Added handler from restarting ```prometheus.service```.
> Improved robutness and more consistent syntax.

- roles/datahandling/tasks/main.yml
We need the handlers at this point, other ways  the subsequent tasks will fail.
> Added forgotten flush_handlers.

- group_vars/hyperchicken-cluster/vars.yml
- roles/interfaces/defaults/main.yml
- roles/interfaces/handlers/main.yml
- roles/interfaces/tasks/main.yml
- roles/interfaces/templates/interface_template.j2
- single_role_playbooks/interfaces.yml
- works for DHCP only at the moment
for static ip it will create a dummy ifcfg file,  but to  add a fixed IP per machine the role needs some additional work.
> configure interfaces

- roles/cluster/tasks/main.yml
Required for various scripts/tools/monitoring tools:
* bc
* dos2unix (includes also mac2unix)
> Install additional standard software on all cluster machines.

- group_vars/gearshift-cluster/vars.yml
- group_vars/talos-cluster/vars.yml
- roles/sudoers/tasks/main.yml
- roles/sudoers/templates/92-ansible-managed
* Improved ```sudoers``` role, so sudo rights will also get revoked when a functional account is no longer specified in ```group_vars/${clustername}/vars.yml```.
* Expanded list of groups, functional accounts and mount points for Gearshift. 
* Updated ```motd``` for clusters in beta with new EOS dates.
> Improved sudoers role and minor related updates.

- cluster.yml
Should have been deployed on DAI + UI, but was listed erroneously for DAI + compute nodes.
> Fixed bug: moved build-environment role to correct position in play.

- roles/slurm-management/files/cgroup.conf
* Do not constrain kernel memory space as this causes issues with shared storage clients.
* Removed settings from older Slurm versions that are longer used.
> Bugfix: Updated cgroup.conf for Slurm

- cluster.yml
- roles/grafana/handlers/main.yml
- roles/grafana/meta/main.yml
- roles/grafana/tasks/main.yml
- roles/grafana/templates/grafana.service
- single_role_playbooks/grafana.yml
I wanted to have grafana to make it easier to compare system stats between the virtual compute nodes.
Running it alongside Prometheus, inside the cluster means we don't need to punch holes in the firewall.
For now, to view the website we do need a ssh tunnel, however.
For more information, see here, for instance:
https://linuxize.com/post/how-to-setup-ssh-tunneling/
> Created role for grafana on the cluster.

- group_vars/talos-cluster/vars.yml
- roles/subgroup_directories/tasks/create_subgroup_directories.yml
- roles/subgroup_directories/tasks/main.yml
- single_role_playbooks/subgroup_directories.yml
* Can be used without root permissions now: this does require the user running the playbook to be able to become the *-dm users for all groups that have subgroup dirs.
* Removed unused LDAP query.
* Wrapped long LDAP query lines for readability.
* Added check to skip remainder of create_subgroup_directories.yml when a group does not have any subgroups.
> Updated subgroup_directories role.

- roles/slurm-management/files/logrotate_slurm
During debugging i found out that logrotation was not working since december 12.
An attempt at manual rotation learned that an endscript entry was needed.
This pull request adds that entry. 
root@imperator 0 $ logrotate -vdf  /etc/logrotate.d/slurm
reading config file /etc/logrotate.d/slurm
error: /etc/logrotate.d/slurm:prerotate, postrotate or preremove without endscript
removing last 1 log configs
> Since December 12 logrotation of slurm was broken.

- group_vars/talos-cluster/vars.yml
- roles/slurm-client/tasks/main.yml
- roles/slurm-management/defaults/main.yml
- roles/slurm-management/tasks/main.yml
- roles/slurm-management/templates/slurm.conf
* Consistent quoting of strings in tasks of `slurm-*` roles.
* Always restart `slurmctld` after a restart of `slurmdbd` to fix "_user does not exist error_".
* Added `slurm_allow_jobs_to_span_nodes` variable to control whether jobs can span multiple nodes or not.
> Updated slurm config.

- group_vars/talos-cluster/vars.yml
- roles/slurm-client/tasks/main.yml
- roles/slurm-management/tasks/main.yml
- roles/slurm-management/templates/slurm.conf
* Fixed missing new `MaxNodes` definition for partition regular.
* Always `restart` Slurm daemons when `slurm.conf` has changed. (For some changes a `reload` is enough, but for others like changes to nodes or partitions a `restart` is required.)
* Added missing local disk space value for Talos slurm config.
> Slurm fixes

- group_vars/gearshift-cluster/vars.yml
- heat/heat_cluster.yml
We changed the specs of the login node to that of a compute node minus the volume on /local.
> Beefing up the user interface.

- roles/slurm-client/tasks/main.yml
- roles/slurm-management/tasks/main.yml
- roles/slurm-management/templates/91-slurm
Added sudoers config to allow users from the functional_admins_group to become the slurm user.
> Slurm admins without root

- roles/slurm-management/files/cgroup.conf
Tweak `swappiness` for Slurm's cgroups:
* Override OS default `swappiness` for Slurm cgroups and set it to `zero`.
* Explicitly set default of 0 for `AllowedSwapSpace`.
> Swappiness

- group_vars/gearshift-cluster/vars.yml
We changed the socket count to two. By doing 
openstack flavor set  24C-220GB     --property hw:cpu_sockets=2
Hopefully this will improve perfomance as the guest kernel can take the numa layout into account.
The first machine rolled out with this setting is gearshift, hence this pull request.
And of course, a new vm wouldn't be complete without a minute change in available ram.
> New vars for new ui.

- roles/cluster/tasks/main.yml
* Need to check rsync version on both control host as well as on the managed hosts.
* Fixed order: install rsync using yum on the managed hosts first before checking the rsync version.
> Fixed order and rsync version checks.

- roles/logins/files/set_quota.sh
- roles/logins/handlers/jumphost-quota.yml
- roles/logins/handlers/main.yml
- roles/logins/tasks/jumphost-quota.yml
- roles/logins/tasks/main.yml
- single_role_playbooks/logins.yml
This will prevent regular users from accidentally transferring large files to the jumphost as opposed to the UI or some other machine.
> Implemented tiny quota for regular (non-admin) users on jumphosts.

- group_vars/all/vars.yml
Becasause of the relocation of the inventory, the ca_keypair_dir s no longer a subdirectory of the inventory. 
This change has been tested to work.
> The inventory dir changed. fixed reference.

- roles/firewall/vars/main.yml
- roles/grafana_proxy/templates/nginx.conf
443 was reserved for incoming ssh on airlock, so we're listening at 3000.
> Allow incoming slurm traffic.

- group_vars/gearshift_cluster/vars.yml
- roles/resolver/defaults/main.yml
- roles/resolver/templates/dnsmasq.conf.j2
Make sure dnsmasq only sends dns queries for the hpc.local domain to the DNS server that knows about it
If it sends it to one of the other upstream nameservers we could be caching an nxdomain or incorrect response
> Set isilon DNS as upstream for hpc.local domain on gearshift

- ansible.cfg
- roles/logins/handlers/main.yml
We use a cronjob to regulary restart DBus and systemd-logind in the correct order as workaround for a known bug that will delay logins and privilege escalation using sudo by ~22 seconds. However you may get an Ansible error:
```
Timeout (12s) waiting for privilege escalation prompt.
```
when the playbook needs privilege escalation before it managed to deploy the workaround. Increasing the timeout makes sure it won't fail in that case.
> Increase timeout as workaround for known DBus bug.

- group_vars/docs.yml
Add `jumphost+docs` as valid server names to the signed host key of the `docs` server for all `jumphosts` we use as the `docs` server is shared for all clusters. Without this fix, the host key is resigned for a different `jumphost+docs` combination each time the `ssh_host_signer` role is executed for another cluster, which will then cause issues when trying to deploy the online_docs role for any of the other clusters.
> Fix signed host key of docs server.

- group_vars/talos_cluster/vars.yml
The channel argument does not do anything, but leaving the old value in the group_vars was confusing too.
> Updated spacewalk channel for Talos.

- group_vars/gearshift_cluster/vars.yml
> Fixed missing umcg- prefix for group name in mount point.

- group_vars/gearshift_cluster/vars.yml
After this update most groups will have a setup where:
* Either members of a `groupname-dms` group for data managers can become the `groupname-dm` user of the corresponding group.
* All members of the group can become the the `groupname-dm` user.
This allows us to manage who can sudo and who cannot by adding users to or removing users from groups in the account management system. And hence does not require a sys admin to redeploy the `sudoers` role for each and every update.
IDVault entries were already added/updated to work with the changes in this pull request.
> Updated sudoers config for Gearshift.

- roles/cluster/meta/main.yml
- roles/cluster/tasks/main.yml
- roles/figlet_motd/meta/main.yml
- roles/online_docs/meta/main.yml
- roles/online_docs/tasks/main.yml
- roles/rsync/tasks/main.yml
- roles/rsyncd/tasks/main.yml
* Fixed code that checks if working `rsync` version is present on both managed and control hosts:
* Improved handling of exceptions when `rsync` is not found.  
* Moved code to check for working `rsync` version to separate role to reduce redundancy.
* Made all roles that use the ansible `synchronize` task (and hence which depend on rsync) depend on the new `rsync` role:
* `cluster`
* `figlet_motd`
* `online_docs`
> Improved rsync handling

- .circleci/config.yml
ansible-linter 5.x requires explicit config for which ansible version to install: use latest ansible with community collections and optional yamllint support.
> Updated CircleCI config for new ansible-linter 5.0.0

- group_vars/gearshift_cluster/vars.yml
- roles/datahandling/tasks/main.yml
We found that the ordering of the kernels is not the same across
instances.
> Pin kernel by name.

- deploy-os_servers.yml
- group_vars/calculon_cluster/vars.yml
* Temporarily added tag to skip task suffering from know bug. Can be removed again once the bug is fixed.
* Added floating IP of new lobby jumphost to group_vars for Calculon.
> Updates for new lobby jumphost

- roles/subgroup_directories/tasks/create_subgroup_directories.yml
Prevents finding `pg-umcg-asedeep` erroneously as subgroup for group `umcg-as` due to missing `^` to anchor search pattern at the beginning of the input strings.
> Simplified and improved regexes to find subgroups.

- roles/slurm_client/tasks/main.yml
- roles/slurm_management/tasks/main.yml
Let systemd automagically detect the PID of any running Slurm daemons as that is more robust. Sometimes the PID files are not written (yet) or get lost resulting in failures when trying to (re)start Slurm daemons.
> Disable PID files for all Slurm daemons.

- group_vars/gearshift_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
Allow sysops to test cluster functionality without requiring access to data from other groups.
> Create prm, tmp and rsc mounts for umcg-sysops group

- group_vars/talos_cluster/vars.yml
- roles/slurm_management/files/slurm.prolog
* Fixed Slurm prolog, where `$SLURM_JOB_QOS` does not exist.
* Fixed config errors for **_Talos_** that would result in NHC taking nodes offline.
> Slurm configuration fixes.

- roles/slurm_management/files/slurm.taskprolog
Making variables readonly is not possible in the slurm.taskprolog.
> Fixed setting TMOUT env variable in slurm.taskprolog.

- inventory.py
The import from test.test_sax fails after following the instructions. Since the start function is not used it can be removed.
> The import from test.test_sax fails after following the instructions.

- generate_secrets.py
The ; in passwords can break command-line usage, like for example in the pulp playbooks.
> Adjust characters used in passphrases

- roles/rsyncd/templates/rsyncd_data_transfer_only_group.conf
- roles/sshd/templates/sshd_config
* `roles/rsyncd/templates/rsyncd_data_transfer_only_group.conf`: replaced `%RSYNC_USER_NAME%` variable, which remains empty in our setup, with `%USER%` variable, which does work.
> Bugfix for chrooted rsync

- group_vars/nibbler_cluster/vars.yml
- roles/slurm_management/files/slurm.taskprolog
- roles/slurm_management/templates/slurm.conf
- roles/slurm_management/templates/slurmdbd.conf
Feature: Make Slurm accounts case insensitive in preparation for account names based on email addresses from _**SURF SRAM**_, which may contain uppercase characters.
Some additional bugfixes, which were required to test the feature above on _Nibbler_:
* Fixed wrong values for resources of _Nibbler_ compute nodes.
* Fixed typo in comment in `slurm.taskprolog`.
* Fixed bug in jinja expression to check for `slurm_allow_jobs_to_span_nodes` in `slurm.conf`.
> Feature: case insensitive slurm accounts

- group_vars/gearshift_cluster/ip_addresses.yml
- group_vars/nibbler_cluster/ip_addresses.yml
- group_vars/talos_cluster/ip_addresses.yml
- group_vars/template/ip_addresses.yml.j2
- static_inventories/gearshift_hosts.ini
- static_inventories/talos_hosts.ini
* Added info for new `tl-repo` and `gs-repo` machines for Pulp.
* Added missing `desc` keys to several `ip_addresses.yml` files as well as to the template in `group_vars/template/ip_addresses.yml.j21`
> Added info for new tl-repo and gs-repo machines for Pulp.

- group_vars/gearshift_cluster/vars.yml
* Added new `umcg-rehabiliation` group on Gearshift. 
* Temporarily disabled `umcgst02` (`dh2`) hosting `prm03` folders to prevent the playbook from switching this file system from _read-only_ to _read-write_ while we migrate this data to new `dh4` Lustre silo.
> Added new umcg-rehabiliation group on Gearshift. 

- group_vars/gearshift_cluster/vars.yml
Because the issues with prm03 will take more time to resolve we temporarily relocate the EGA Fuse client mounts to prm02. (They do not work when prm03 is read-only.)
> Temporarily relocated EGA Fuse client mounts prm03 -> prm02

- group_vars/nibbler_cluster/ip_addresses.yml
- group_vars/nibbler_cluster/vars.yml
- roles/online_docs/templates/mkdocs/docs/dedicated-dt-server-overview.md
- static_inventories/nibbler_hosts.ini
* The _Nibbler_ jumphost and dedicated data transfer server now use DNS entries.
* This has already been deployed by re-running the `ssh_host_signer` and `online_docs roles`
> Updates for DNS entries for Nibbler.

- roles/nfs_server/tasks/main.yml
Required to overcome the infamous NFS 16 group limit.
> Fix to allow NFS to lookup GIDs.

- .circleci/config.yml
* Do not waste resources on Circle CI: downgraded to single core image as test code is single threaded and cannot use additional cores.
* Updated to new Circle CI "convenience image" for Python. (The previously used "legacy" image will be deprecated on 2021-12-31.)
> Updated Circle CI config.

- documentation/Configuring_Pulp.md
Documentation update:
* Simplified Pulp repo server installation using new features from `pulp-cli`.
* Made repo management more idempotent: do not create a new publication if we already have a publication for a certain repo version.
> Pulp simplified

- group_vars/gearshift_cluster/vars.yml
Note: code is still commented out as dh4 Lustre silo cannot be used yet: need network changes to enable jumbo frames and need updated Lustre client.
> Updated Lustre source address for umcgst02 from dh2 silo -> dh4 silo.

- roles/online_docs/tasks/main.yml
- roles/online_docs/templates/apache/redirect_all_http_to_https.conf
- static_inventories/fender_cluster.ini
- static_inventories/gearshift_cluster.ini
- static_inventories/hyperchicken_cluster.ini
- static_inventories/marvin_cluster.ini
- static_inventories/nibbler_cluster.ini
- static_inventories/talos_cluster.ini
- static_inventories/wingedhelix_cluster.ini
* Removed old documentation server from static inventories.
* Enabled HTTPS for docs.gcc.rug.nl
* And redirect HTTP -> HTTPS to enforce a secure connection.
Note:
* PR contains hard coded FQDN for docs.gcc.rug.nl in 2 places. There is currently no nice way to store this in group_vars. Will need the rewritten dynamic inventory.py with support for host specific vars in the static inventories to improve this.
* Certificate and corresponding private key is manually deployed on the server and not using the playbook.
> Feature: ssl for online docs

- roles/logins/tasks/main.yml
Added patch for `/etc/pam.d/sshd` to allow logins from users in the `admin` group using ssh even when `/etc/nologin` is present. This way we can
* set /etc/nologin during maintenance to prevent regular users to login 
* and still deploy ansible playbooks using an unprivileged account from the admin group in combination with sudo to act as root user.
> Added patch for /etc/pam.d/sshd to allow logins from admins.

- roles/lustre_client/templates/lustre.conf
Datahandling 4 is now mounted on gs-vcompute01
This was done by installing the packages build by whamcloud by hand. These should be included in pulp We did not need to build any packages.  So perhaps we can omit the build dependencies.
The packages can be found here:
https://downloads.whamcloud.com/public/lustre/latest-2.12-release/el7/client/RPMS/x86_64/
The manual command used was:
yum --disablerepo=* reinstall lustre-client-2.12.8_6_g5457c37-1.el7.x86_64.rpm kmod-lustre-client-2.12.8_6_g5457c37-1.el7.x86_64.rpm
Mounting can be done like so. As you can se, the group mounts have not yet been changed,
172.23.57.213@tcp14:172.23.57.214@tcp14:/umcg /mnt/ lustre  defaults,_netdev,flock  0 0
> [Inclomplete]: Changed to new lustre configuration syntax.

- group_vars/gearshift_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
- roles/ega_fuse_client/tasks/main.yml
Fix: use normal Java dependency from Linux distro/OS as opposed to hacky one from /apps, which may not be there yet. Was previously already implemented for Hyperchicken and Fender. Now also enabled for Talos and Gearshift now that they also get their repos from a local Pulp server.
> Improved Java for EGA Fuse client

- ansible.cfg
For proper re-use of sockets for SSH connection multiplexing.
> Changed Ansible "default" to OpenSSH default SSH ControlPath

- roles/slurm_management/templates/slurm.conf
This means jobs that were submitted, but are not eligible for scheduling due to an unsatisfied dependency, will not accumulate "wait time" for the `Age` job priority factor. In other words, only jobs that can start immediately and are waiting for resources to become available will accrue "wait time" resulting in a higher weight for the `Age` factor of their priority. With `ACCRUE_ALWAYS` enabled workflow management systems like NextFlow that use "just in time" job submission would be penalized compared to others that just submit all jobs (including ones with dependencies on other jobs) for an entire workflow at once.
> Removed ACCRUE_ALWAYS PriorityFlag for Slurm scheduler.

- roles/sshd/defaults/main.yml
- roles/sshd/templates/sshd_config
Tweaked `LoginGraceTime` and `MaxSessions` depending on _inventory group_ to prevent issues with `MaxStartups` especially on _jumphosts_.
> Improved sshd_config template

- roles/subgroup_directories/tasks/create_subgroup_directories.yml
Enforce write permission in the `releases` and `projects` folder only for the functional data manager accounts.
> Fix permissions for "releases" and "projects" folder when a group uses sub groups.

- README.md
- ansible.cfg
- lor-init
- roles/subgroup_directories/tasks/create_subgroup_directories.yml
- roles/subgroup_directories/tasks/main.yml
Improved speed:
* Refactored ```subgroup_directories``` role:
* Removed redundant tasks.
* Added ```set -o pipefail``` for ```ansible.builtin.shell``` tasks and make sure ```grep``` does not make the ansible task failed when the exit status is 1 (no results found).
* Added support for Mitogen strategy plugin for Ansible
* Updated ```lor-init```: detects whether Mitogen is installed and ```lor-config``` will enable it automatically when installed.
* Updated ```README.md``` with instructions to install Mitogen.
* Tested for ```ansible-playbook single_role_playbooks/subgroup_directories.yml``` on _Gearshift_:
* Without Mitogen installed and with redundant tasks:
```
PLAY RECAP
****************************************************************************************************
gearshift: …
```
> Refactored subgroup_directories role to remove redundant tasks and improve speed.

- static_inventories/talos_cluster.yml
(VM was lost in translation from `ini `to `yaml` based inventories.)
> Re-added missing tl-repo server to Talos inventory.

- roles/slurm_management/templates/slurm.conf.updated_for_slurm-21.08.x
Note: created a temporary `slurm.conf.updated_for_slurm-21.08.x` which will be moved to `slurm.conf` later on when it is time to upgrade (not now).
* Changed the names of a few parameters.
* Removed parameters that are not supported anymore.
* Removed unused, commented parameters.
> Added new slurm.conf updated for 21.08.x.

- roles/ldap/tasks/main.yml
- roles/sssd/tasks/main.yml
- single_role_playbooks/ldap.yml
- single_role_playbooks/sssd.yml
* ```sssd``` role: Do not fail on disabling ```nslcd.service``` task when ```nslcd``` does not exist on a machine.
* Always (re-)run ```sshd``` role after potentially changing the logic to fetch public keys.
* Included ```sshd``` role in ```single_role_playbooks/ldap.yml``` and ```single_role_playbooks/sssd.yml```
* Removed code to only redeploy ```sshd.conf``` in ```roles/ldap/tasks/main.yml``` and ```roles/sssd/tasks/main.yml``` as that will fail when the ```sshd``` role is not included in a play -> resulting in missing defaults/vars for the sshd role and used in that ```sshd.conf```file.
> Fixed some dependencies

- static_inventories/wingedhelix_cluster.yml
Added into static inventories the missing `nfs_server` for Wingedhelix cluster
> WH: NFS fix

- group_vars/nibbler_cluster/ip_addresses.yml
Nibblers vcompute[01-04] have been recreated because openstack had issues. Here are the new IP's.
> Nibbler: redeploy vcomputes after OS issues

- static_inventories/wingedhelix_cluster.yml
The playbook was failing, as default values of geerlingguy.security were conflicting with settings for 2FA.
The `security_ssh_challenge_response_auth` is by default set to `no`, while for the `Porch` we need it to be `yes`.
> WH: geerlingguy.security fix sshd_config 2FA

- group_vars/gearshift_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
_Gearshift_ and _Talos_ clusters: Added missing network ID vars required for lookup of IP addresses in a.o. the ```static_hostname_lookup``` role.
> Gearshift and Talos: Added missing network ID vars.

- roles/yum_local/defaults/main.yml
- roles/yum_local/tasks/main.yml
- single_group_playbooks/cluster_part1.yml
- changed repo folder from /var/local/repo to /usr/local/repo as (based on linux's filesystem hierarchy standard) it fits better there
- fixed main task triggering to be executed when truly needed:
- inside the playbook and
- when running single_group/cluster_part1 playbook
> yum_local: relocate directory and fix triggers

- roles/swap/tasks/disable_swap.yml
- roles/swap/tasks/enable_swap.yml
- single_group_playbooks/repo.yml
- single_role_playbooks/swap.yml
- static_inventories/nibbler_cluster.yml
- static_inventories/wingedhelix_cluster.yml
* Added swap role to `repo` _inventory group_.
* Adjusted `swap_file_size` for `wh-repo` and `nb-repo` as the default is too large.
Required to prevent the small `wh-repo` and `nb-repo` VMs from running out of memory when syncing _Pulp_ repos with their remotes.
> Fix: swap for repo vms

- group_vars/marvin_cluster/vars.yml
- group_vars/nibbler_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
- group_vars/wingedhelix_cluster/vars.yml
- roles/slurm_management/tasks/main.yml
* For Nibbler, Talos, Winged Helix and Marvin.
* Also added task to `slurm_management` role to delete unused Slurm RPMs.
> Upgraded Slurm 20.11.8-1.el7.umcg -> 22.05.2-1.el7.umcg for various clusters

- README.md
- create-docs-server.yml
- create-jenkins-server.yml
- deploy-os_servers.yml
- requirements.yml
* Freeze version numbers for `OpenStack SDK` & _Ansible_ `openstack.cloud` _collection_:  
Prevent update to too new `OpenStack SDK` >= 0.99.0, which breaks backwards compatibility for older OpenStack clouds.
* Added workaround for missing security groups when new servers are created: assign security groups to network ports.
> Freeze OpenStack versions and fix for missing security groups.

- roles/cluster/defaults/main.yml
- roles/cluster/tasks/main.yml
For example `Betabarrel` might not need `irods-icommand` package (at least not now). It expects to install it, but fails as we didn't add `irods` repository to `Betabarrel`.
This commit converts static list of packages to a variable that can be easily overwritten for individual cluster or just a server (inside `group_vars` or `static_inventory`).
> Changed a list of packages into variable that can be defined per cluster/server

- group_vars/wingedhelix_cluster/vars.yml
Added functional_users_group on Winged Helix. This group can be included in `/etc/security/access.conf` by _MIT_ on the new `wh-chaperone`.
> Added functional_users_group on Winged Helix.

- group_vars/all/vars.yml
- roles/sudoers/templates/92-ansible-managed
- static_inventories/wingedhelix_cluster.yml
* Improvement: Escape spaces in group names where necessary for a role (e.g. `sudoers`), but not in the _value_ itself.
* Bugfix: Added missing GID for `umcg-funus` group.
* Bugfix: Do not create the `functional_admin_group` locally on `wh-chaperone`, because it comes from the UMCG AD.
* Removed `umcg-lab` group from `wh-chaperone`, because it is not used.
> Fixes for Winged Helix

- group_vars/irods.yml
- static_inventories/nibbler_cluster.yml
Fixes variable precedence for variables used by `ssh_host_signer` and `iptables` roles on `irods` machines.
> Fixed issue with variable values not getting picked up from the static inventory due to precedence.

- group_vars/betabarrel_cluster/vars.yml
I have checked what was missing from the BB configuration (in comparison to the WH) as the `vars.yml` were copied few weeks ago, and since then there were some changes in the list of users (and so ansible-pipelines were crashing due to missing users).
Please note that some groups in WH were removed while other just commented out. Please look at the group `umcg-gst`.
Perhaps there is a good reason for that?
> Betabarrel added missing configuration

- roles/slurm_management/files/job_submit.lua
Bugfix: only check job meta data values if they are not ```nil```, which may be the case for optional meta data items like ```#SBATCH --error``` and ```#SBATCH --output```.
Note: deployed and tested on _Hyperchicken_
> Bugfix for roles/slurm_management/files/job_submit.lua

- static_inventories/betabarrel_cluster.yml
- static_inventories/copperfist_cluster.yml
- static_inventories/docs_library.yml
- static_inventories/fender_cluster.yml
- static_inventories/forkhead_cluster.yml
- static_inventories/gearshift_cluster.yml
- static_inventories/hyperchicken_cluster.yml
- static_inventories/jenkins_server.yml
- static_inventories/marvin_cluster.yml
- static_inventories/nibbler_cluster.yml
- static_inventories/talos_cluster.yml
- static_inventories/wingedhelix_cluster.yml
Ansible will fail if it cannot find Python in ```/usr/bin/python``` when using ```connection: local```. Recent versions of macOS removed _Python 2_ from ```/usr/bin/python``` and only have a ```/usr/bin/python3```. The workaround is to
* Create a symlink .../python3 -> .../python somewhere in a location that is listed in your ```$PATH```
* Make sure Ansible will look for ```/usr/bin/env python``` instead of ```/usr/bin/python```, which is arranged in this PR.
> Workaround for Ansible control hosts that do not have Python installed in /usr/bin/python.

- group_vars/betabarrel_cluster/vars.yml
Like forkhead: updated slurm version for Betabarrel and it also uses new slurm template that supports slurm-in-a-box configuration.
Already deployed and working on Betabarrel.
> Betabarrel: updated slurm to new version

- group_vars/betabarrel_cluster/vars.yml
- group_vars/copperfist_cluster/vars.yml
- roles/smb_server/tasks/main.yml
* Added code to create path for Samba shares if it does not already exist.
* Updated Copper Fist and Beta Barrel group_vars for recently updated functionality.
> Added missing functionality for Samba shares.

- roles/mariadb/handlers/main.yml
- roles/mariadb/tasks/main.yml
- roles/slurm_management/templates/slurm.conf.22.05.2-1.el7.umcg
If submitted jobs fail, it dependent job stay in queue with status `DependencyNeverSatisfied`. Currently user has to either add additional `#SLURM` parameter that says that the jobs should be cleand OR user has to clean the jobs manually via `scancel`.
I checked the documentation of slurm configuration and found out that there is a setting called `DependencyParameters` that has option `kill_invalid_depend`, which does exactly this.
Other: fixed some other minor ansible-lint issues.
> Slurm: kill jobs that has invalid dependencies

- README.md
- deploy-os_servers.yml
- group_vars/fender_cluster/vars.yml
- group_vars/hyperchicken_cluster/vars.yml
* `README.md`: Added missing python dependency required for playbooks that create OpenStack components.
* Added extra _security group_ for storage VLAN.
* Updated _Hyperchicken_ and _Fender_ configs to use extra storage VLAN security group.
Note:
* Already deployed and tested on _Hyperchicken_
* Not yet deployed on _Fender_ as it would require stopping and starting VMs, so we need to schedule and announce maintenance.
> Create storage network security group.

- roles/online_docs/tasks/main.yml
Temporarily disabled `use_ssh_args: true` in `roles/online_docs/tasks/main.yml`, because it is causing issues with the latest _Mitogen_ version and we can run playbooks successfully without it.
> Temporarily disabled "use_ssh_args: true".

- group_vars/gearshift_cluster/vars.yml
Robin enabled project quota on `DH4`, so we can now switch the `prm03` folders from group to project quota.
> Switched prm03 from group to project quota.

- roles/shared_storage/templates/ldapquota.bash
Make minimal hard quota limit higher than minimal soft limit to prevent issues on Isilon systems.
> Improved handling of minimal quota limits.

- roles/sssd/templates/get_public_keys_from_ldap.bash
Bugfix for handling LDAP servers that send multiple SSH public key attributes (one for each public key) per account as opposed to multiple public keys in a single attribute.
> Bugfix for handling multipe public key LDAP attributes.

- roles/lustre_client/tasks/install.yml
- single_group_playbooks/pre_deploy_checks.yml
- single_role_playbooks/openstack_computing.yml
- single_role_playbooks/openstack_networking.yml
* Fixed vars list -> dict in `openstack* single_role_playbooks`
* Implemented timeout & retry for fetching Ansible dependencies from `requirements.yml` in `single_group_playbooks/pre_deploy_checks.yml`.
* `lustre_client` role: Fixed (re)boot order dependency.
> Small improvements

- .circleci/config.yml
- static_inventories/betabarrel_cluster.yml
- static_inventories/copperfist_cluster.yml
- static_inventories/wingedhelix_cluster.yml
* [Added chaperone aliases in a comment in static_inventories.](https://github.com/rug-cit-hpc/league-of-robots/commit/ff4540d1e78fc98cb6f80e9ac05de6f67f4ca168)
* [Switched ansible-lint to offline mode in CircleCI config to prevent redundantly resolving dependencies with "ansible-galaxy install -r requirements.yml" with a high chance of failing, because of silly timeouts.](https://github.com/rug-cit-hpc/league-of-robots/commit/813a4d913123753735df1846b01e6c60e9eea3dd)
> Chaperone aliases and attempt at making CircleCI jobs with ansible-lint more robust

- roles/envsync/tasks/main.yml
- roles/online_docs/templates/attachments/ssh-client-config.bash
- roles/online_docs/templates/mkdocs/docs/logins-linux-config.md
- roles/regular_users/defaults/main.yml
- roles/regular_users/tasks/functional_accounts_on_chaperones.yml
- roles/regular_users/tasks/main.yml
- roles/regular_users/templates/ssh_client_config.j2
* Added code to configure `~/.bashrc` and `~/.ssh/...` for functional accounts on chaperones.
* Send STDOUT from envsync cronjobs to `/var/log/messages` using `logger`.
> Improved configuration of functional accounts on chaperone machines.

- group_vars/gearshift_cluster/vars.yml
- roles/shared_storage/tasks/main.yml
* Data Handling Lustre migration to new data center part 1: [Switched dh1 mounts from read-write to read-only.](https://github.com/rug-cit-hpc/league-of-robots/pull/764/commits/a3646cbd2a2c216bff083f1e22a8b00482c9b7ad)
[a3646cb](https://github.com/rug-cit-hpc/league-of-robots/pull/764/commits/a3646cbd2a2c216bff083f1e22a8b00482c9b7ad)
* `shared_storage` role: [added defaults to handle empty lists and added option to mount prm file systems read-only.](https://github.com/rug-cit-hpc/league-of-robots/pull/764/commits/06bf12b6673316db55bb96d93aac521c842cd3e5)
[06bf12b](https://github.com/rug-cit-hpc/league-of-robots/pull/764/commits/06bf12b6673316db55bb96d93aac521c842cd3e5)
> Dh migration part1

- group_vars/gearshift_cluster/vars.yml
Switched `umcgst01` and `umcgst03` temporarily from `dh1` to `dh4` for migration of `dh1` to new data center.
> Data Handling dh1 migration part 2.
