- group_vars/gearshift/vars.yml
I copied the relevant sections from slurm.conf as it is already rolled out on gearshift.
> Made a gearshift vars file.

- group_vars/gearshift/vars.yml
- roles/slurm/files/slurm.conf
They are now less wrong, but exact specs of nodes may be still off...
First step in fixing #2
> Updated slurm configs

- hyperchicken_hosts
- roles/cluster/tasks/main.yml
- roles/cluster/templates/gearshift_hosts
- roles/cluster/templates/hyperchicken_hosts
- roles/cluster/templates/talos_hosts
Temporary set headnode as the jumphost for testing
> tmp hc hosts fix

- users.yml
> gcc users should have a user cabable of sudo on

- cluster.yml
- roles/cluster/tasks/main.yml
- roles/compute-vm/tasks/main.yml
- roles/spacewalk_client/handlers/main.yml
- roles/spacewalk_client/tasks/main.yml
- users.yml
* Fixed perms on /local.
* Re-ordered RPMs in alphabetic order.
> Minor improvements.

- cluster.yml
- group_vars/gearshift-cluster/vars.yml
- group_vars/hyperchicken-cluster/vars.yml
- group_vars/talos-cluster/vars.yml
- resolver.yml
- roles/resolver/handlers/main.yml
- roles/resolver/tasks/main.yml
- roles/resolver/templates/dnsmasq.conf.j2
Resolver role configures dnsmasq to use the nameservers listed in group_vars for a cluster.
> Added new resolver role.

- cluster.yml
See below for one description of the bug.
https://bugs.launchpad.net/ubuntu/+source/systemd/+bug/1591411
> Added workaround for a bug in logind.

- cluster.yml
- group_vars/administration.yml
- roles/mount-volume/defaults/main.yml
- roles/mount-volume/tasks/main.yml
- single_role_playbooks/mount-volume.yml
It now mounts the volume for boths adnin interfaces and virtual compute nodes.
> Made the role more generic

- group_vars/all/vars.yml
Added a new key for kees. This account is used by the security check "stealth"
> Added new key for kees (stealth)

- roles/cluster/templates/sshd_config
Two more lines are actually ldap related.
> The ldapwrapper is for situations with ldap only

- group_vars/template/secrets.yml
- group_vars/template/vars.yml
Added missing secrets that were intruduced after the creation of the template.
> Added missing secrets from gearshift.

- group_vars/gearshift-cluster/vars.yml
- heat/talos.yml
- roles/online_docs/handlers/main.yml
- roles/online_docs/tasks/main.yml
- roles/online_docs/templates/mkdocs/docs/index.md
- roles/online_docs/templates/mkdocs/mkdocs.yml
- single_role_playbooks/online_docs.yml
- talos_hosts.ini
@erijpkema can you assign IP addresses to tl-docs in heat/talos.yml?
> Added initial version of generated online docs (work in progress).

- fender_hosts.ini
- group_vars/fender-cluster/vars.yml
- group_vars/hyperchicken-cluster/vars.yml
- hyperchicken_hosts.ini
* Shrink Hyperchicken and grow Fender.
* Seperate shared storage for Hyperchicken and Fender: use different PFS for each.
> For clusters @ Embassy: Resized clusters and fixed shared storage config.

- group_vars/fender-cluster/vars.yml
- group_vars/gearshift-cluster/vars.yml
- group_vars/hyperchicken-cluster/vars.yml
- group_vars/talos-cluster/vars.yml
- roles/envsync/tasks/main.yml
- roles/envsync/templates/hpc-environment-permissions.bash
* Added cron jobs to run hpc-environment-sync.bash and hpc-environment-permissions.bash daily overnight.
> Improved envsync role

- deploy-os_servers.yaml
- fender_hosts.ini
- group_vars/all/vars.yml
- group_vars/fender-cluster/vars.yml
- ldap_regular_users.yml
- roles/cluster/templates/fender_hosts
- single_role_playbooks/dai.yml
- a playbook for filling local openldap.
- fix: Fender tmpname form tmp09 to tmp10.
> Playbook for filling local openldap, and Fender tmpname fix

- group_vars/all/vars.yml
Added public ssh key from Fokke Dijkstra.
> Added public ssh key from Fokke Dijkstra.

- cluster.yml
- roles/cluster/tasks/main.yml
* Added installation of unzip rpm
* Added missing figlet_hostname role for UIs: fixes #144.
> Minor fixes

- roles/build-environment/tasks/generic-build-dependencies.yml
- roles/cluster/tasks/main.yml
* Added gnutls and openssl to build environment.
* Added check for rsync version to cluster role.
> Extra RPMs for build environment and rsync version check.

- .lorrc
- ansible.cfg
Added ```.lorrc file``` that provides a function ```lor-config``` to configure the environment for deploying a specific cluster: less typing!
> Less typing on the commandline to deploy clusters.

- group_vars/all/vars.yml
- group_vars/fender-cluster/vars.yml
- roles/online_docs/templates/mkdocs/docs/index.md
- roles/online_docs/templates/mkdocs/docs/logins.md
Added quickstart and windows documentation
> Added quickstart and windows documentation

- group_vars/gearshift-cluster/vars.yml
- roles/online_docs/templates/mkdocs/docs/specifications.md
> Fixed wrong local disk size on Gearshift compute nodes.

- .circleci/config.yml
- roles/cluster/tasks/build_lustre_client.yml
> Show the actual ci errors and fixed an error:

- cluster.yml
- group_vars/all/vars.yml
- roles/yum-repos/tasks/main.yml
Moved adding of custom repos from task to role to ensure it is executed in the correct role order.
> Custom yum repos from task -> role.

- roles/slurm-client/tasks/main.yml
- roles/slurm-management/tasks/main.yml
- roles/spacewalk_client/tasks/main.yml
* Ensure we install custom, patched Slurm RPMs and
* Make sure they are not replaced by more recent, unpatched versions during a system upgrade.
> Bugfix for yum configs

- group_vars/all/vars.yml
- group_vars/talos-cluster/vars.yml
- roles/build-environment/tasks/generic-build-dependencies.yml
* Some packages may be listed as part of the ```development``` package group... or not. Yum behaves in _mysterious ways_, so we now list several packages explicitly. Maybe we should stop using package groups all together.
* Added admin account for Kim on Talos cluster.
> Added missing tools to generic build environment and adde new user.

- roles/slurm-management/files/logrotate_slurm
- roles/slurm-management/tasks/main.yml
Add logrotate for the slurm logfiles.
> Add logrotate for slurm.

- roles/slurm-management/files/logrotate_slurm
Thanks, Pieter for pointing out that we use systemd now....
> Updated to systemd.

- roles/build-environment/tasks/generic-build-dependencies.yml
- roles/cluster/tasks/main.yml
So we can compile tools that were build with the Qt framework.
> Added Qt5.

- group_vars/boxy-cluster/vars.yml
- group_vars/fender-cluster/vars.yml
- group_vars/hyperchicken-cluster/vars.yml
- group_vars/marvin-cluster/vars.yml
- group_vars/nibbler-cluster/vars.yml
For other clusters that had not been updated for recent changes in the shared_storage role.
> Updated pfs_mounts and lfs_mounts variables in group_vars

- roles/mariadb/files/innodb.cnf
- roles/mariadb/tasks/main.yml
https://wiki.fysik.dtu.dk/niflheim/Slurm_database
Related to topdesk call 
I2003-04676
> Implemented innodb recomendations after ER_LOCK_WAIT_TIMEOUT error.

- roles/mariadb/files/innodb.cnf
- roles/mariadb/tasks/main.yml
These commits by Egon were already merged, but after some rebasing to split a larger pull request into smaller ones, git now wants to remerge these.
Implemented innodb recomendations after ER_LOCK_WAIT_TIMEOUT error.
https://wiki.fysik.dtu.dk/niflheim/Slurm_database
> Git drove me nuts.

- group_vars/gearshift-cluster/vars.yml
- group_vars/talos-cluster/vars.yml
- roles/shared_storage/defaults/main.yml
- roles/shared_storage/tasks/main.yml
- roles/shared_storage/templates/ldapquota.bash
Configures quota based on limits retrieved from the LDAP.
> First implementation of script to configure lustre project quota

- group_vars/jumphost.yml
Pull request for ssl will follow.
> Opened port 3000

- roles/online_docs/templates/mkdocs/docs/logins-linux.md
Replaced hard-coded jumphost value with ansible templated variable.
> Fixed bug on docs for Linux users.

- group_vars/gearshift_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
* Removed outdated notifications from MOTD
* updated `sudoers` config for umcg-franke-scrna group.
> Assorted small updates

- README.md
- roles/online_docs/tasks/main.yml
- roles/online_docs/templates/attachments/ssh-client-config.bash
- roles/online_docs/templates/mkdocs/docs/logins-linux-config.md
* Added and documented option to use different user for jumphost than the one used to ssh to a destination server behind a jumphost.
* Bugfix: Escape bash variables in ssh client config script
* Bugfix: Remove redundant lines in ssh client config script
* Bugfix: Add handler to rebuild website with mkdocs when attachments have changed. Otherwise the updated attachments won't get deployed.
> Bugfix: tweaked deploy order and added option to use different user for login to jumphost. 

- group_vars/gearshift_cluster/vars.yml
- roles/datahandling/templates/lustre.conf
Of course, memory is about to change again, but running ansible without the currently correct value will break things
> Fix Gearshift group vars

- group_vars/gearshift_cluster/vars.yml
set correct/new memory size and add missing interface
> Update gearshift group vars

- .gitignore
- group_vars/gearshift_cluster/vars.yml
*  Added `*-openrc.sh` OpenStack SDK/API configuration files for projects to `.gitignore`.
* Updated sudoers config for `umcg-gastrocol` group on _Gearshift_.
> Small assorted updates

- roles/build_environment/tasks/generic_build_dependencies.yml
- roles/cluster/tasks/main.yml
> Added libsodium and accompanying libsodium-devel for cryptography.

- .circleci/config.yml
- deploy-os_servers.yml
* Updated _circleci_ config to also lint `deploy-os_servers.yml` playbook.
* Fixed a few linter errors in `deploy-os_servers.yml` playbook.
> Updated CI config

- single_role_playbooks/datahandling.yml
I thought this was already committed. But it wasn't
> A single role playbook for datahandling.

- galaxy-requirements.yml
- roles/regular_users/tasks/ldap_regular_users.yml
changes in task calls
ldap_attr > community.general.ldap_attr
and into the galaxy_requirements.yml
> Updated the ldap task call to be compatible with newer standards

- roles/logrotate/tasks/main.yml
- single_group_playbooks/cluster_part1.yml
- single_group_playbooks/docs.yml
- single_group_playbooks/jumphost.yml
- single_group_playbooks/repo.yml
- single_role_playbooks/logrotate.yml
* Ensure `logrotate` is installed.
* Enable compression for old logs, which saves a lot of space on the system partition.
> Added logrotate role.

- roles/envsync/tasks/main.yml
- roles/pulp_server/tasks/main.yml
Fixed bug where Ansible would hang waiting for su to return, which would never happen.
> Fix for correct initialization of home dirs.

- deploy-os_servers.yml
- group_vars/calculon_cluster/vars.yml
- group_vars/fender_cluster/vars.yml
- group_vars/gearshift_cluster/vars.yml
- group_vars/hyperchicken_cluster/vars.yml
- group_vars/marvin_cluster/vars.yml
- group_vars/nibbler_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
- roles/ldap/defaults/main.yml
And removed unused
```
ldap_port: '389'
ldaps_port: '636'
```
variables.
> Switched Nibbler to new and from Merlin accessible LDAP.

- group_vars/template/users.yml
Fixes https://github.com/rug-cit-hpc/league-of-robots/issues/449
> Added group_vars/template/users.yml.

- documentation/Configuring_Pulp.md
- group_vars/gearshift_cluster/vars.yml
- group_vars/talos_cluster/vars.yml
- roles/online_docs/meta/main.yml
* Updated _Pulp_ documentation: Included code to automate manual steps not yet supported by _Pulp Squeezer_.
* Switched _Talos_ clients from _SpaceWalk_ to _Pulp_ for repo management.
> Pulp updates

- roles/admin_users/tasks/main.yml
- roles/sshd/defaults/main.yml
- roles/sshd/tasks/enable_totps.yml
- roles/sshd/templates/totp-auth
- roles/sshd/templates/totp_config.sh
* Relocated totp config files from `~/.totp` to `~/.ssh/totp` to prevent issues with SELinux.
* Make sure home dirs for admin users are correctly labelled for SELinux.
> Improved sshd role

- group_vars/betabarrel_cluster/vars.yml
As already successfully deployed on the BB.
> Betabarrel: fix mounts and changed backup destination

- roles/yum_local/README.md
- roles/yum_local/templates/README
Added yumdownloader command, and made both READMEs a bit more readable
> Yum local: readme simple update

- group_vars/all/vars.yml
- roles/static_hostname_lookup/templates/hosts.j2
- static_inventories/nibbler_cluster.yml
Include all relevant IPs of machines instead of only the ones for the first management network.
> Improved /etc/hosts files.

- group_vars/gearshift_cluster/vars.yml
> Removed umcg-mmbimg group.

- roles/slurm/templates/slurm.conf.22.05.2-1.el7.umcg
Copy-paste from new Habrok config.
> Added CommunicationParameters option to increase Slurm security.

- roles/listserv/templates/LDAP2LISTSERV.bash
Bugfix for handling the case when a subscribed cluster user has an account that is still active, but no longer has an email address configured in the LDAP.
> Bugfix for LDAP2LISTSERV.bash
